#version 450

layout (rgba8, location = 0) readonly  uniform image2D u_image_input;
layout (rgba8, location = 1) writeonly uniform image2D u_image_output;
layout (r8,    location = 2) readonly  uniform image2D u_image_noise;

layout (location = 3) uniform bool  u_vertical;
layout (location = 4) uniform int   u_samples;
layout (location = 5) uniform ivec4 u_rect;
layout (location = 6) uniform float u_border_radius;
layout (location = 7) uniform float u_weights[32];

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

float sdf_rounded_box(vec2 p, vec2 b, float r) {
	vec2 q = abs(p) - b + r;
	return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r;
}

vec4 image_read(ivec2 coord, ivec2 image_size) {
	coord.y = image_size.y - coord.y - 1;
	coord   = clamp(coord, ivec2(0), image_size - 1);
	return imageLoad(u_image_input, coord);
}

void main() {
	ivec2 min = u_rect.xy;
	ivec2 max = u_rect.zw;

	if (!u_vertical) {
		min.y -= u_samples;
		max.y += u_samples;
	}

	ivec2 invocation = ivec2(gl_GlobalInvocationID.xy);
	ivec2 coord      = invocation + min;
	ivec2 image_size = imageSize(u_image_input);
	if (coord.x >= max.x || coord.y >= max.y) {
		return;
	}
	if (coord.x < 0 || coord.y < 0) {
		return;
	}

	vec4  acc    = image_read(coord, image_size) * u_weights[0];
	ivec2 offset = u_vertical ? ivec2(0, 1) : ivec2(1, 0);
	for (int i = 1; i < u_samples; i += 1) {
		acc += image_read(coord + i * offset, image_size) * u_weights[i];
		acc += image_read(coord - i * offset, image_size) * u_weights[i];
	}

	coord.y = image_size.y - coord.y - 1;
	if (u_vertical) {
		float noise = imageLoad(u_image_noise, invocation % imageSize(u_image_noise)).r;
		acc        += 0.005 * (noise - 0.5);

		vec2  rect_size = vec2(max - min);
		float box       = sdf_rounded_box(vec2(invocation) - rect_size / 2.0, rect_size / 2.0, u_border_radius);

		if (box > 0.0) {
			return;
		} else if (box > -1.0) {
			// NOTE: we don't really need to do AA here since we usually draw an AAd box over this anyway
			// imageStore(u_image_output, coord, acc * -box);
		} else {
			imageStore(u_image_output, coord, acc);
		}
	} else {
		imageStore(u_image_output, coord, acc);
	}
}
